coverage:
  status:
    project:
      default:
        target: auto  # Compare coverage to the previous base commit (PR base or parent commit)
        informational: false  # If true, status will always pass

ignore:
  - "setup.py"
  - "src/gsy_e/setup/*"
  - "src/gsy_e/resources/*"
  - "vagrant/*"
  - "wiki/*"
  - "tools/*"
  - "requirements/*"

comment:
  layout: "diff"
  behavior: default
