Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.gui = true
    v.cpus = 2
  end
 config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git python3 python3-pip nodejs build-essential openssl libssl-dev libffi-dev lubuntu-desktop 
    npm install -g npm
    apt-get update
    apt-get upgrade -y
    apt-get autoremove -y
    
    export REPO=gridsingularity/d3a
    export BRANCH=master

    git clone -b ${BRANCH} https://gsydev:f91220d94bb884c6175f67070b0ff0e2ee542710@github.com/${REPO}.git /app
    cd /app
    pip3 install --upgrade setuptools
    pip3 install -r/app/requirements/dev.txt &&  pip3 install -e .
  SHELL
end
