Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
 config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq openssl libssl-dev
    sudo apt-get install -yq build-essential libffi-dev redis git-core software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt-get update
    sudo apt-get install python3.6 -y
    sudo apt-get install git-core -y
    sudo apt-get install python3-pip -y
    sudo apt-get install python3-setuptools -y
  SHELL
  config.vm.synced_folder ".", "/vagrant/"
end
