WATER_SPECIFIC_HEAT_CAPACITY = 4182  # [J/kg°C]
SPECIFIC_HEAT_CONST_WATER = 0.00116  # [kWh / (K * kg)]
SPECIFIC_HEAT_CAPACITY_WATER = 4200  # [J / kg / K]
WATER_DENSITY = 1  # [kg / l]

DEFAULT_SOURCE_TEMPERATURE_C = 12
