name: gsy-e-license-check
on:
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/tests.txt
          pip install pip-licenses

      - name: Check dependency licenses
        run: python tools/check_licenses.py
